---
# tasks file for roles/hive
- name: Download hive 3.1.2
  command: "wget -P ~ https://downloads.apache.org/hive/hive-3.1.2/apache-hive-3.1.2-bin.tar.gz"

- name: Untar downloaded version
  command: "sudo tar xzvf apache-hive-3.1.2-bin.tar.gz"

- name: Changing hive folder
  become: true
  command: "mv apache-hive-3.1.2-bin /usr/local/hive"

- name: Changing owner to hive folder
  become: true
  command: "chown {{user}}:{{user}} -R /usr/local/hive"

- name: adding HIVE HOME
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HIVE_HOME=/usr/local/hive

- name: adding PATH
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export PATH=$PATH:$HIVE_HOME/bin

- name: Configure core-site file
  become: true
  template:
    src: "core-site.xml.j2"
    dest: "/usr/local/hadoop/etc/hadoop/core-site.xml"

- name: create hive directories on hdfs
  command: "hdfs dfs -mkdir /hive"

- name: create hive warehouse route
  command: "hdfs dfs -mkdir -p /hive/warehouse"

- name: create hive tmp
  command: "hdfs dfs -mkdir -p /tmp"

- name: hive tmp perm
  command: "hdfs dfs -chmod g+w /tmp"

- name: hive warehouse perm
  command: "hdfs dfs -chmod g+w /hive/warehouse"

- name: Configuring hive
  become: true
  command: "cp /usr/local/hive/conf/hive-env.sh.template /usr/local/hive/conf/hive-env.sh"

- name: Configuring hive
  lineinfile:
    dest: "/usr/local/hive/conf/hive-env.sh"
    insertafter: EOF
    state: present
    line:
      export HADOOP_HOME=/usr/local/hadoop

- name: Configuring hive
  lineinfile:
    dest: "/usr/local/hive/conf/hive-env.sh"
    insertafter: EOF
    state: present
    line:
      export HIVE_CONF_DIR=/usr/local/hive/conf

- name: Install mysql server
  become: true
  command: "apt-get update -y"

- name: Ensure required packages are installed
  become: true
  apt:
    name:
      - mysql-server
    state: latest

- name: enable mysql
  become: true
  command: "systemctl enable mysql"

- name: Install mysql java
  become: true
  command: "apt-get install libmysql-java -y"


- name: link
  become: true
  command: "ln -s /usr/share/java/mysql-connector-java.jar /usr/local/hive/lib/mysql-connector-java.jar"

- name: Ensure required packages are installed
  become: true
  apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python-pip
      - gcc
      - libsasl2-dev
      - libsasl2-2
      - libsasl2-modules-gssapi-mit
      - php7.2-cli
      - php-pgsql
      - php-pdo-pgsql
      - php-xsl
      - php-mbstring
      - php-intl
    state: latest

- name: Install Required pip3 modules
  pip:
    name:
      - PyMySQL
      - ez_setup
      - setuptools
      - petl
      - pandas
      - cdata
      - PyHive
      - thrift
      - sasl
      - thrift-sasl
      - pyhs2
      - Jaydebeapi
      - jupyter
    state: present
    executable: pip3

# - name: Install Required pip modules
#   pip:
#     name:
#       - petl
#     state: present
#     executable: pip

- name: Add my.cnf to user home
  become: true
  command:  "cp /etc/mysql/debian.cnf ."

- name: Add my.cnf to user home
  become: true
  command:  "chown ubuntu:ubuntu debian.cnf"

- name: Remove anonymous users
  command: |
    mysql --defaults-file=debian.cnf -ne "{{ item }}"
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Remove test database and access to it
  command: |
    mysql --defaults-file=debian.cnf -ne "{{ item }}"
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: Reload privilege tables
  command: |
    mysql --defaults-file=debian.cnf -ne "{{ item }}"
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: update root pw
  command: |
    mysql --defaults-file=debian.cnf -ne "{{ item }}"
  with_items:
    - ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}'
  changed_when: False


- name: Create new database
  command: |
    mysql --defaults-file=debian.cnf -ne "{{ item }}"
  with_items:
    - CREATE DATABASE metastore;
  changed_when: False

- name: import database
  command: |
    mysql --defaults-file=debian.cnf -ne "{{ item }}"
  with_items:
    - USE metastore;SOURCE /usr/local/hive/scripts/metastore/upgrade/mysql/hive-schema-3.1.0.mysql.sql;
  changed_when: False

- name: Create database user
  command: |
    mysql --defaults-file=debian.cnf -ne "{{ item }}"
  with_items:
    - CREATE USER 'hiveuser'@'%' IDENTIFIED BY 'hivepassword';
    - GRANT all on *.* to 'hiveuser'@localhost identified by 'hivepassword';
    - flush privileges;
  changed_when: False

- name: Configuring hive metastore
  become: true
  template: src=hive-site.xml.j2 dest=/usr/local/hive/conf/hive-site.xml

- name: hive service
  become: true
  copy:
    src: "hive-meta.service"
    dest: "/etc/systemd/system/hive-meta.service"

- name: enable hive service
  become: true
  command: "systemctl start hive-meta.service"

- name: enable hive service
  become: true
  command: "systemctl enable hive-meta.service"

- name: source ~/.bashrc
  shell: source ~/.bashrc
  args:
    executable: /bin/bash


- name: fixing guava
  become: true
  command: "rm /usr/local/hive/lib/guava-19.0.jar"

- name: fixing guava
  become: true
  command: "cp /usr/local/hadoop/share/hadoop/hdfs/lib/guava-27.0-jre.jar /usr/local/hive/lib/"


- name: metastore
  become: true
  command: "cp /usr/local/hadoop/share/hadoop/hdfs/lib/guava-27.0-jre.jar /usr/local/hive/lib/"


#   ############################################################



  ############################################################