---
#========== AWS Setting (aws image) 
region: us-east-2
vpc_name: bustamante
key_name: govsol-2021
#ubuntu 18.04 ami-03a0c45ebc70f98ea
image_name: ami-03a0c45ebc70f98ea
#huerelease: release-4.10.0
cleanup_cloud: true
dns_zone: ansible.local
ttl: 60
public_volume_size: 20
private_volume_size: 20
public_instance_type: t2.xlarge
private_instance_type: t2.xlarge
private_instance_b2b_b2c: t2.2xlarge
cidr_block: 172.30.0.0/16
cidr_pub_1: 172.30.16.0/20
cidr_pub_2: 172.30.32.0/20
cidr_pri_1: 172.30.128.0/24
cidr_pri_2: 172.30.254.0/24
az_1: us-east-2a
az_2: us-east-2b


##### Note: Make sure that number_masters_az_1 + number_masters_az_2 = number_masters and number_datanodes_az_1 + number_datanodes_az_2 = number_datanodes
number_masters: 1
number_datanodes: 2
number_hives: 1
number_pigs: 1
number_sparks: 1
number_sqoops: 1
number_b2bdatas: 1
# number_oozies: 1
# number_hues: 1
number_masters_az_1: 1
number_masters_az_2: 0
number_datanodes_az_1: 2
number_datanodes_az_2: 0
number_hives_az_1: 1
number_hives_az_2: 0
number_pigs_az_1: 1
number_pigs_az_2: 0
number_sparks_az_1: 1
number_sparks_az_2: 0
number_sqoops_az_1: 1
number_sqoops_az_2: 0
number_b2bdatas_az_1: 1
number_b2bdatas_az_2: 0
# number_oozies_az_1: 1
# number_oozies_az_2: 0
# number_hues_az_1: 1
# number_hues_az_2: 0

path_hosts_group: inventories/staging
private_key: /home/sabb/govsol-2021.pem 
# Must be absolute path to your private key
python_pkgs:
        - boto
        - boto3

#========== Bastion host
bastion_ip: 3.14.187.224
user: ubuntu
ansible_ssh_common_args: '-o ProxyCommand="ssh -i {{ private_key }} -W %h:%p -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no {{ user }}@{{ bastion_ip }}"'
mysql_root_password: root

hadoop_folder: '/usr/local/hadoop/data'
internal_public_key_hadoop: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDav7rluOgQezG45loKoNkx9S0iaT+5EmdPvxu+ir2+E065wds7TRp3Xd1k7mk4C8E1P/la3t/renAV8sBdyYC4OT1x/d7pEjjudzFAKD4XdVPsQ8n3z2IxzHLoaXoBjnKHM4Kc28l/KQY3cTSlr/DdeRg82CruodegIFHsefMiPjU1TclinO5w6OvvdcwsQVxe3yGfWarQq/eKTDLw/RLx2pPCxyrRijs7xGXNU1BEWtyAUdc6poqhc3nxh9rNmoroUaMWU90oGmbYUiAC8krirL2t7bHwVprAhgdOXtBBIQVKHZastneDksKzA4Mx0UANHa3SYP6+zxqpv/tFc4TDhnWMQYUdzjPsuK0LtUfMQw1Pw+cB7y8VDixslPy701aGQ0mXhG8fVdymCko3GJErx7xwSp8v1ngdYlViXQRUNOlLGhi8ALvRmSCEJ69BLXOAzfWsk/UdAfhbUg+XBskRFhL+aDn9NAqw5WdSGGjwnRu6Qm55b9ifBPnXc1ME/Es='
