---
#tasks file for hadoop_master
- name: Configure core-site file
  become: true
  template:
    src: "core-site.xml.j2"
    dest: "/usr/local/hadoop/etc/hadoop/core-site.xml"

- name: Configure hdfs-site file
  become: true
  template:
    src: "hdfs-site.xml.j2"
    dest: "/usr/local/hadoop/etc/hadoop/hdfs-site.xml"

- name: Configure mapred-site file
  become: true
  template:
    src: "mapred-site.xml.j2"
    dest: "/usr/local/hadoop/etc/hadoop/mapred-site.xml"

- name: Configure yarn-site file
  become: true
  template:
    src: "yarn-site.xml.j2"
    dest: "/usr/local/hadoop/etc/hadoop/yarn-site.xml"

- name: Configure workers
  become: true
  template:
    src: "workers.j2"
    dest: "/usr/local/hadoop/etc/hadoop/workers"

- name: Creating Directory for namenode
  file:
    path: "{{ hadoop_folder }}"
    state: directory

- name: source /etc/environment
  shell: source /etc/environment
  args:
    executable: /bin/bash

- name: adding HDFS_NAMENODE_USER
  become: false
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HDFS_NAMENODE_USER="ubuntu" 

- name: adding HDFS_DATANODE_USER
  become: false
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:      
      export HDFS_DATANODE_USER="ubuntu"

- name: adding HDFS_SECONDARYNAMENODE_USER
  become: false
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HDFS_SECONDARYNAMENODE_USER="ubuntu"
      
- name: adding YARN_RESOURCEMANAGER_USER
  become: false
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export YARN_RESOURCEMANAGER_USER="ubuntu"

- name: adding YARN_NODEMANAGER_USER
  become: false
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export YARN_NODEMANAGER_USER="ubuntu"

- name: adding HADOOP HOME ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_HOME="/usr/local/hadoop"

- name: adding HADOOP COMMON ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_COMMON_HOME=$HADOOP_HOME

- name: adding HADOOP CONF ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

- name: adding HADOOP HDFS ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_HDFS_HOME=$HADOOP_HOME

- name: adding HADOOP MAPRED ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_MAPRED_HOME=$HADOOP_HOME

- name: adding HADOOP YARN ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_YARN_HOME=$HADOOP_HOME

- name: source ~/.bashrc
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
      
- name: Wait 1 minute before start service
  pause:
    minutes: 1
###############################################
- name: format hdfs namenode
  shell: "echo Y | hadoop namenode -format"
  args:
    executable: /bin/bash

- name: start hadoop service
  shell: "start-dfs.sh"
  #args:
  #  executable: /bin/bash

- name: start yarn service
  shell: "start-yarn.sh"
  #args:
  #  executable: /bin/bash
###############################################
