---
#tasks file for hadoop_master
# - name: Update ubuntu repositories on master
#   become: true
#   command: "apt-get update -y"

# - name: Install java 8
#   become: true
#   command: "apt install openjdk-8-jdk -y"

# - name: Download Hadoop 3.2.1 from public repositories
#   command: "wget -P ~ https://archive.apache.org/dist/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz"

# # UNCOMMENT ABOVE COMMAND AND COMMENT NEXT COMMAND IF YOU WANT TO DOWNLOAD DIRECTLY FROM APACHE

# # - name: copying Hadoop 3.2.1 from local 
# #   copy:
# #     src: "hadoop-3.2.1.tar.gz"
# #     dest: "/home/ubuntu/hadoop-3.2.1.tar.gz"

# - name: Untar downloaded version
#   command: "sudo tar xzf hadoop-3.2.1.tar.gz"

# - name: Changing folder name
#   command: "mv /home/ubuntu/hadoop-3.2.1 /home/ubuntu/hadoop"

# - name: Configure JAVA_HOME on hadoop-env.sh file 
#   become: true
#   copy:
#     src: "hadoop-env.sh"
#     dest: "/home/ubuntu/hadoop/etc/hadoop/hadoop-env.sh"

# - name: Changing hadoop folder
#   become: true
#   command: "mv /home/ubuntu/hadoop /usr/local/hadoop"

# - name: create logs folder
#   become: true
#   command: "mkdir -p /usr/local/hadoop/logs"

# - name: Changing owner to hadoop folder
#   become: true
#   command: "chown {{user}}:{{user}} -R /usr/local/hadoop"

# - name: Setting path environment
#   become: true
#   copy:
#     src: "environment"
#     dest: "/etc/environment"

# - name: source /etc/environment
#   shell: source /etc/environment
#   args:
#     executable: /bin/bash

# - name: Verifying JAVA_HOME
#   command: "echo $JAVA_HOME"

- name: Configure core-site file
  become: true
  template:
    src: "core-site.xml.j2"
    dest: "/usr/local/hadoop/etc/hadoop/core-site.xml"

- name: Configure hdfs-site file
  become: true
  template:
    src: "hdfs-site.xml.j2"
    dest: "/usr/local/hadoop/etc/hadoop/hdfs-site.xml"

- name: Configure workers
  become: true
  template:
    src: "workers.j2"
    dest: "/usr/local/hadoop/etc/hadoop/workers"

- name: Creating Directory for namenode
  file:
    path: "{{ hadoop_folder }}"
    state: directory

- name: source /etc/environment
  shell: source /etc/environment
  args:
    executable: /bin/bash

- name: adding HDFS_NAMENODE_USER
  become: false
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HDFS_NAMENODE_USER="ubuntu" 

- name: adding HDFS_DATANODE_USER
  become: false
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:      
      export HDFS_DATANODE_USER="ubuntu"

- name: adding HDFS_SECONDARYNAMENODE_USER
  become: false
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HDFS_SECONDARYNAMENODE_USER="ubuntu"
      
- name: adding YARN_RESOURCEMANAGER_USER
  become: false
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export YARN_RESOURCEMANAGER_USER="ubuntu"

- name: adding YARN_NODEMANAGER_USER
  become: false
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export YARN_NODEMANAGER_USER="ubuntu"

# - name: adding pdsh environment
#   lineinfile:
#     dest: "~/.bashrc"
#     insertafter: EOF
#     state: present
#     line:
#       export PDSH_RCMD_TYPE=ssh

- name: adding HADOOP HOME ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_HOME="/usr/local/hadoop"

- name: adding HADOOP COMMON ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_COMMON_HOME=$HADOOP_HOME

- name: adding HADOOP CONF ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

- name: adding HADOOP HDFS ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_HDFS_HOME=$HADOOP_HOME

- name: adding HADOOP MAPRED ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_MAPRED_HOME=$HADOOP_HOME

- name: adding HADOOP YARN ENVIRONMENT
  lineinfile:
    dest: "~/.bashrc"
    insertafter: EOF
    state: present
    line:
      export HADOOP_YARN_HOME=$HADOOP_HOME

- name: source ~/.bashrc
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
      
- name: Wait 1 minute before start service
  pause:
    minutes: 1
###############################################
- name: format hdfs namenode
  shell: "echo Y | hadoop namenode -format"
  args:
    executable: /bin/bash

- name: start hadoop service
  shell: "start-dfs.sh"
  #args:
  #  executable: /bin/bash

- name: start yarn service
  shell: "start-yarn.sh"
  #args:
  #  executable: /bin/bash
###############################################


# - name: Set hostname for individual host
#   template: src=hostname.j2 dest=/etc/hostname

# - name: ensure that the new hostname is preserved between restarts/reboots
#   command: "echo preserve_hostname: true >> /etc/cloud/cloud.cfg"

# - name: Update hostname without reboot server
#   shell: 'sudo hostname -F /etc/hostname'

# - name: Add hostname fqdn
#   template: src=hosts.j2 dest=/etc/hosts

# - name: Creating user for hadoop
#   command: "adduser --disabled-password --gecos '' huser"

# - name: Creating group for hadoop
#   command: "groupadd hadoopuser"

# - name: Permissions to huser
#   command: "usermod -aG hadoopuser huser"

# - name: Changing owner to hadoop folder 
#   command: "chown huser:root -R /usr/local/hadoop/" 
  
# - name: Changind permissions to hadoop folder
#   command: "chmod g+rwx -R /usr/local/hadoop/"

# - name: adding user to sudoerlist
#   command: "adduser huser sudo"

# - name: Changing user to huser
#   command: "sudo su - huser"

#- name: Creating ssh key for huser
#  command: "ssh-keygen -t rsa"




# tasks file for hadoop_master
# - name: Download Java Software
#   get_url:
#     url: https://mirrors.huaweicloud.com/java/jdk/8u202-b08/jdk-8u202-linux-x64.rpm
#     dest: /root/java.rpm

# - name: Download Hadoop Software
#   get_url:
#     url: https://archive.apache.org/dist/hadoop/core/hadoop-3.3.1/hadoop-3.3.1.tar.gz
#     dest: /root/hadoop.tar.gz

# - name: Install Java
#   command : "rpm -i /root/{{ item }} --force"
#   loop: "{{ pkgs_name }}"

# - name: Untar to /opt
#   command : "tar -zxvf {{ item }} -C /opt"
#   loop: "{{ hadoop_installer }}"

# - name: Configure core-site file 
#   copy:
#     src: "core-site.xml"
#     dest: "/etc/hadoop/core-site.xml"

# - name: Configure hdfs-site file 
#   template:
#     src: "hdfs-site.xml.j2"
#     dest: "/etc/hadoop/hdfs-site.xml"
        
# - name: Creting Directory for namenode
#   file:
#     path: "{{ hadoop_folder }}"
#     state: directory
    
# - name: Hadoop Namenode Format    
#   shell: "echo Y | hadoop namenode -format"

# - name: Starting Namenode Service
#   shell: "hadoop-daemon.sh start namenode"

# - name: Making Hadoop Daemon Service Permanent
#   lineinfile:
#     path: /etc/rc.d/rc.local
#     line: hadoop-daemon.sh start namenode
#     mode: '0755'
