---

- name: Wait some minutes for report
  pause:
    minutes: 3

- name: Facts public EC2 instance
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Role": bastion
      instance-state-name: running
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: public_ec2_facts

- name: Facts private EC2 instance
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Role": datanode
      instance-state-name: running
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: datanode_private_ec2_facts

- name: Facts private EC2 instance
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Role": master
      instance-state-name: running
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: master_private_ec2_facts

- name: Facts private EC2 instance
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Role": hive
      instance-state-name: running
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: hive_private_ec2_facts

- name: Facts private EC2 instance
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Role": pig
      instance-state-name: running
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: pig_private_ec2_facts

- name: Facts private EC2 instance
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Role": spark
      instance-state-name: running
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: spark_private_ec2_facts

- name: Facts private EC2 instance
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Role": sqoop
      instance-state-name: running
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: sqoop_private_ec2_facts

- name: Facts private EC2 instance
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Role": b2bdata
      instance-state-name: running
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: b2bdata_private_ec2_facts


# - name: Facts private EC2 instance
#   ec2_instance_info:
#     region: "{{ region }}"
#     filters:
#       "tag:Role": oozie
#       instance-state-name: running
#     aws_access_key: "{{ access_key }}"
#     aws_secret_key: "{{ secret_key }}"
#   register: oozie_private_ec2_facts

# - name: Facts private EC2 instance
#   ec2_instance_info:
#     region: "{{ region }}"
#     filters:
#       "tag:Role": hue
#       instance-state-name: running
#     aws_access_key: "{{ access_key }}"
#     aws_secret_key: "{{ secret_key }}"
#   register: hue_private_ec2_facts

- name: Clean content inventories file
  shell: echo " " > "{{ path_hosts_group }}"/hosts

- name: Clean content of datanode inventories file
  shell: echo " " > "{{ path_hosts_group }}"/namenode

- name: Write Namenodes
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[masternodes]"


- name: Write Namenodes
  lineinfile:
    dest: "{{ path_hosts_group }}/namenode"
    insertafter: EOF
    state: present
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
  with_together: 
        - "{{ master_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
        - "{{ master_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 


- name: Merger namenodenode file to host inventories
  shell: 'cat {{ path_hosts_group }}/namenode >> {{ path_hosts_group }}/hosts'


- name: Write Datanodes
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[datanodes]"

- name: Write Datanodes
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
    state: present
    create: yes
  with_together: 
        - "{{ datanode_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
        - "{{ datanode_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

- name: Write Hive Servers
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[hives]"

- name: Write Hive Servers
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
    state: present
    create: yes
  with_together: 
        - "{{ hive_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
        - "{{ hive_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

- name: Write Pig Servers
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[pigs]"

- name: Write Pig Servers
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
    state: present
    create: yes
  with_together: 
        - "{{ pig_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
        - "{{ pig_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

- name: Write Spark Servers
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[sparks]"

- name: Write Spark Servers
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
    state: present
    create: yes
  with_together: 
        - "{{ spark_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
        - "{{ spark_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

- name: Write Sqoop Servers
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[sqoops]"

- name: Write Sqoop Servers
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
    state: present
    create: yes
  with_together: 
        - "{{ sqoop_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
        - "{{ sqoop_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

- name: Write b2bdata Servers
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[b2bdatas]"

- name: Write b2bdata Servers
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
    state: present
    create: yes
  with_together: 
        - "{{ b2bdata_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
        - "{{ b2bdata_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

# - name: Write Oozie Servers
#   lineinfile:
#     dest: "{{ path_hosts_group }}/hosts"
#     insertafter: EOF
#     line: "[oozies]"

# - name: Write Oozie Servers
#   lineinfile:
#     dest: "{{ path_hosts_group }}/hosts"
#     insertafter: EOF
#     line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
#     state: present
#     create: yes
#   with_together: 
#         - "{{ oozie_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
#         - "{{ oozie_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

# - name: Write Hue Servers
#   lineinfile:
#     dest: "{{ path_hosts_group }}/hosts"
#     insertafter: EOF
#     line: "[hues]"

# - name: Write Hue Servers
#   lineinfile:
#     dest: "{{ path_hosts_group }}/hosts"
#     insertafter: EOF
#     line: "{{ item.0 }} ansible_ssh_host={{ item.1 }}"
#     state: present
#     create: yes
#   with_together: 
#         - "{{ hue_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
#         - "{{ hue_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 


# - name: Change ambari server IP
#   lineinfile:
#     dest: "group_vars/all.yaml"
#     regexp: '^var_ambari_server: '
#     line: 'var_ambari_server: {{ item.0 }}'
#   with_together: 
#         - "{{ (master_private_ec2_facts.instances|map(attribute='private_ip_address')|list)[0] }}" 

- name: Update basion host
  lineinfile:
    dest: "group_vars/all.yaml"
    regexp: '^bastion_ip: '
    line: 'bastion_ip: {{ item.0 }}'
  with_together: 
        - "{{ (public_ec2_facts.instances|map(attribute='public_ip_address')|list)[0] }}" 

- name: Write ssh common args group
  lineinfile:
    dest: "{{ path_hosts_group }}/hosts"
    insertafter: EOF
    line: "[all:vars]"        

#- name: Wite ssh common args
#  shell: echo "ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> "{{ path_hosts_group }}"/hosts    

- name: Write ssh common args
  shell: echo "ansible_ssh_common_args='{{ ansible_ssh_common_args }}'" >> "{{ path_hosts_group }}"/hosts  

- name: Clean proxies
  shell: echo "" > "{{ path_hosts_group }}"/proxies

- name: generate hadoop proxy for master
  lineinfile:
    dest: "{{ path_hosts_group }}/proxies"
    insertafter: EOF
    line: "{{ item.0 }} ==>  ssh -i {{ private_key }} -L 9870:{{ item.1}}:9870 {{user}}@{{bastion_ip}}" 
  with_together: 
    - "{{ master_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
    - "{{ master_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

- name: generate hadoop proxy for datanodes
  lineinfile:
    dest: "{{ path_hosts_group }}/proxies"
    insertafter: EOF
    line: "{{ item.0 }} ==>  ssh -i {{ private_key }} -L 9864:{{ item.1}}:9864 {{user}}@{{bastion_ip}}" 
  with_together: 
    - "{{ datanode_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
    - "{{ datanode_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

- name: generate hadoop proxy for resource manager
  lineinfile:
    dest: "{{ path_hosts_group }}/proxies"
    insertafter: EOF
    line: "{{ item.0 }} ==>  ssh -i {{ private_key }} -L 8088:{{ item.1}}:8088 {{user}}@{{bastion_ip}}"
    state: present
    create: yes
  with_together: 
    - "{{ master_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
    - "{{ master_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 

- name: ssh commands to master host
  lineinfile:
    dest: "{{ path_hosts_group }}/proxies"
    insertafter: EOF
    line: "{{ item.0 }} ==>  ssh {{user}}@{{item.1}}"
    state: present
    create: yes
  with_together: 
    - "{{ master_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
    - "{{ master_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}"

- name: ssh commands to slaves host
  lineinfile:
    dest: "{{ path_hosts_group }}/proxies"
    insertafter: EOF
    line: "{{ item.0 }} ==>  ssh {{user}}@{{item.1}}"
    state: present
    create: yes
  with_together: 
    - "{{ datanode_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
    - "{{ datanode_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}"

- name: ssh commands to hive host
  lineinfile:
    dest: "{{ path_hosts_group }}/proxies"
    insertafter: EOF
    line: "{{ item.0 }} ==>  ssh {{user}}@{{item.1}}"
    state: present
    create: yes
  with_together: 
    - "{{ hive_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
    - "{{ hive_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}"

- name: ssh commands to pig host
  lineinfile:
    dest: "{{ path_hosts_group }}/proxies"
    insertafter: EOF
    line: "{{ item.0 }} ==>  ssh {{user}}@{{item.1}}"
    state: present
    create: yes
  with_together: 
    - "{{ pig_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
    - "{{ pig_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}"

- name: ssh commands to spark host
  lineinfile:
    dest: "{{ path_hosts_group }}/proxies"
    insertafter: EOF
    line: "{{ item.0 }} ==>  ssh {{user}}@{{item.1}}"
    state: present
    create: yes
  with_together: 
    - "{{ spark_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
    - "{{ spark_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}"

- name: ssh commands to sqoop host
  lineinfile:
    dest: "{{ path_hosts_group }}/proxies"
    insertafter: EOF
    line: "{{ item.0 }} ==>  ssh {{user}}@{{item.1}}"
    state: present
    create: yes
  with_together: 
    - "{{ sqoop_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
    - "{{ sqoop_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}"

- name: ssh commands to b2bdata host
  lineinfile:
    dest: "{{ path_hosts_group }}/proxies"
    insertafter: EOF
    line: "{{ item.0 }} ==>  ssh {{user}}@{{item.1}}"
    state: present
    create: yes
  with_together: 
    - "{{ b2bdata_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
    - "{{ b2bdata_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}"

# - name: generate hadoop proxy for oozie
#   lineinfile:
#     dest: "{{ path_hosts_group }}/proxies"
#     insertafter: EOF
#     line: "{{ item.0 }} ==>  ssh -i {{ private_key }} -L 11000:{{ item.1}}:11000 {{user}}@{{bastion_ip}}"
#     state: present
#     create: yes
#   with_together: 
#     - "{{ oozie_private_ec2_facts.instances|map(attribute='tags.Host')|list }}"
#     - "{{ oozie_private_ec2_facts.instances|map(attribute='private_ip_address')|list }}" 